mkdist: create git-commit-id instead of .git/HEAD
.git/HEAD in elinks-0.12pre1.tar.gz broke git-import-orig in Debian's
git-buildpackage 0.4.33:

$ git init
Initialized empty Git repository in .git/
$ git-import-orig ~/src/elinks-seek/elinks-0.12pre1.tar.gz
Upstream version is 0.12pre1
Initial import of '/home/Kalle/src/elinks-seek/elinks-0.12pre1.tar.gz' ...
fatal: bad object HEAD
Traceback (most recent call last):
  File "/usr/bin/git-import-orig", line 243, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/git-import-orig", line 201, in main
    import_upstream_tree(repo, orig_dir, version, options.filters, verbose=not is_empty)
  File "/usr/bin/git-import-orig", line 65, in import_upstream_tree
    if replace_source_tree(repo, src_dir, filters, verbose=True):
  File "/var/lib/python-support/python2.5/gbp/git_utils.py", line 145, in replace_source_tree
    return not repo.is_clean()[0]
  File "/var/lib/python-support/python2.5/gbp/git_utils.py", line 78, in is_clean
    if out[0].startswith('#') and out[1].strip().startswith(clean_msg):
IndexError: list index out of range

So let's try with a "git-commit-id" file outside of .git/ instead.
I also considered ".git-commit-id" but that could give the impression
that Git itself reads the file for some purpose.